spring.application.name=week7CICD


server.port=8080
#JPA defaults(safe for dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.format_sql=true

#Swagger (SpringDoc)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
